# Generated by Django 4.2.19 on 2025-03-30 15:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('password', models.CharField(default='da', max_length=255)),
                ('avatar', models.TextField(default='')),
                ('creation_time', models.TimeField(blank=True, default=datetime.time(18, 51, 16, 77423))),
                ('creation_date', models.DateField(blank=True, default=datetime.date(2025, 3, 30))),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('password', models.CharField(default='da', max_length=255)),
                ('avatar', models.TextField(default='')),
                ('creation_time', models.TimeField(blank=True, default=datetime.time(18, 51, 16, 77076))),
                ('creation_date', models.DateField(blank=True, default=datetime.date(2025, 3, 30))),
                ('location', models.CharField(default='da', max_length=255)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('category', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('measure', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Оплачен', max_length=255)),
                ('time', models.TimeField(blank=True, default=datetime.time(18, 51, 16, 78325))),
                ('date', models.DateField(blank=True, default=datetime.date(2025, 3, 30))),
                ('count', models.IntegerField(default=0)),
                ('measure', models.CharField(default='л', max_length=255)),
                ('price', models.FloatField(default=0)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.buyer')),
                ('farmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.farmer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.farmeritem')),
            ],
        ),
        migrations.CreateModel(
            name='ItemReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=0)),
                ('review', models.TextField(default='')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.buyer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.farmeritem')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.buyer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.farmeritem')),
            ],
        ),
    ]
