# Generated by Django 4.2.7 on 2025-05-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_application_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='company',
        ),
    ]
