# Generated by Django 4.2.7 on 2025-05-15 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_application_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
    ]
