# Generated by Django 4.2.7 on 2025-05-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_application_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='JobApplication',
        ),
    ]
