# Generated by Django 4.2.7 on 2025-05-15 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_application_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='company',
            field=models.ForeignKey(default='Yandex', on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
    ]
