# Generated by Django 4.2.7 on 2025-05-28 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_resumeapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeapplication',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.chat'),
        ),
    ]
