# Generated by Django 4.2.7 on 2025-05-28 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_resumeapplication_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeapplication',
            name='chat',
        ),
    ]
