# Generated by Django 4.2.7 on 2025-05-30 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_resumeapplication_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='resume_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.resumeapplication'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.jobapplication'),
        ),
    ]
