# Generated by Django 4.2.7 on 2025-05-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_chat_resume_application_alter_chat_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
