# Generated by Django 4.2.7 on 2025-06-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auction_all_confirmed_auction_confirmation_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='publish_phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='publish_status',
        ),
    ]
