# Generated by Django 4.2.7 on 2025-06-06 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_newslettersubscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newslettersubscriber',
            old_name='subscribed_at',
            new_name='created_at',
        ),
    ]
